controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
main_page:
    path: /
    controller: App\Controller\mainPageController::index
